// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://prbhdqidoftvhvtyxjjm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InByYmhkcWlkb2Z0dmh2dHl4amptIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk0NDc4MjEsImV4cCI6MjA2NTAyMzgyMX0.eBKyjfq-P-zkvUYkDZC3GGnvUONCBVXsAKZoLRgKnOY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);